---
- name: Playbook for Creating User's
  hosts: all
  become: yes
  tasks:
    - name: Creating User's
      user:
        name: user123
    - name: Storing the Output
      shell: cat /etc/passwd | tail -1
     # command: echo Hi 
      register: chkusr

    - debug:
        msg: "{{ chkusr.stdout }}"
