---
- name: Testing Handlers
  hosts: node1
  become: yes
  tasks:
    - name: Copy file
      copy:      
        src: index.html
        dest: /var/www/html
        backup: yes
      notify: "contents text123"

  handlers:
    - name: contents text123
      service:
        name: apache2
        state: restarted
